apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: train-schedule
  name: train-schedule
spec:
  finalizers:
  - kubernetes

---
  
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
  namespace: train-schedule
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  namespace: train-schedule
  labels:
    app: train-schedule
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
